apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: indian-states
build:
  artifacts:
    - image: gcr.io/careful-form-307204/indian-states
      jib:
        project: com.example:indian-states
deploy:
  kubectl:
    manifests:
      - k8s/mydeployment.yaml
      - k8s/myservice.yaml
