apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: indian-states
build:
  artifacts:
    - image: docker.io/hiashish/indian-states
      jib:
        project: com.example:indian-states
  insecureRegistries:
    - docker.io
deploy:
  kubectl:
    manifests:
      - k8s/mydeployment.yaml
      - k8s/myservice.yaml