name: CI
on:
  push:
    paths:
      - src/**
      - action.yml
      - .github/workflows/**
jobs:
  pipiline:
    name: Pipiline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Minikube
        uses: hiberbee/github-action-minikube@latest

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Skaffold pipeline
        uses: hiberbee/github-action-skaffold@latest
        with:
          filename: test/skaffold.yaml
          command: run
          default-repo: harbor.k8s.hiberbee.net/library

      - name: Get Helm releases
        run: helm list
